### ISSUE TITLE
Chat and Modules invisible

### ISSUE THREAD

**Issue by Creeperlover234** [Hexeption/Youtube-Hacked-Client-1.8#1]
Ok simple fix I would believe. But I don't know lol because i am new to java programing so... But anyway here are some of the screenshots:
Normal with hacks enabled with chat off: http://imgur.com/jEbmvAa
Hacks on with chat enabled: http://imgur.com/kACqjKv
Typing hi in chat and not appearing: http://imgur.com/uSb7BTs

**Comment by iQuintennn** [comment]
There is something wrong with ur Ingame-UI Overlay thats caused by his shitty tutorials i recommend watching ConnorM with his how to code a minecraft hacked client and chose the UI Episode, this works.

**Comment by Hexeption** [comment]
Fixed
