### ISSUE TITLE
Minecraft Running Really Fast From Eclipse

### ISSUE THREAD

**Issue by Masonator4102** [Hexeption/Youtube-Hacked-Client-1.8#15]
For some reason, if I have more than one module  added to the ModuleManager, my minecraft runs at 2x normal speed. My computer runs minecraft fine normally

**Comment by CalebDesignsSites** [comment]
Make sure on the file EntityPlayerSP.java you have this code with public void onUpdate:
//TODO:YOURCLIENTNAME
            for (Module m : YOURCLIENTNAME.theClient.moduleManager.activeModules){
                m.onUpdate();
            }

**Comment by CalebDesignsSites** [comment]
I forgot the m.onUpdate(); part and it ran minecraft at 2x speed. I thought it was the modules, but it isn't.
