### ISSUE TITLE
I dont get it

### ISSUE THREAD

**Issue by Aerodynamicks** [Hexeption/Youtube-Hacked-Client-1.8#16]
how do I open this with eclipse, it is acting strangely

**Comment by CalebDesignsSites** [comment]
Ehh. I'm not too knowledgeable about this kinda stuff about eclipse, but he didn't include the "eclipse" folder that is your workspace with mcp. I am not aware of a way to open it in eclispe, so I just followed his programming tutorials.

**Comment by MonkeyPlayzMC** [comment]
watch his vids again

**Comment by Hexeption** [comment]
Learn how to use Eclipse / an IDE, Also learning Java may help :+1:
