### ISSUE TITLE
Shaders mod on this?

### ISSUE THREAD

**Issue by synchroviron17** [Hexeption/Youtube-Hacked-Client-1.8#6]
I just grabbed all of the semi source classes from the 1.8 shadersmod installer, the import ref.* is just importing all of the obfuscated minecraft classes. ref for reference. I also changed the package declaration to fit my project in eclipse but that's it. I think it would be really cool to have a hacked client with shadersmod in it, if only because I haven't seen one anywhere else.

Link: https://github.com/synchroviron17/shadersmod

**Comment by MonkeyPlayzMC** [comment]
Well optifine already has shaders so there you go there is your answer!

**Comment by MonkeyPlayzMC** [comment]
It comes with shaders
